# Generated by Django 4.2.4 on 2023-08-10 01:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_alter_menuitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='LittleLemonAPI.menuitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
